name: Sync Products Cron Job

    on:
      schedule:
        # Ejecuta todos los días a las 02:00 AM UTC
        # Puedes ajustar este schedule. Por ejemplo, para cada 6 horas: '0 */6 * * *'
        # Para cada 5 minutos (¡úsalo con precaución!): '*/5 * * * *'
        - cron: '0 2 * * *'
      workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions de GitHub

    jobs:
      sync_external_products:
        runs-on: ubuntu-latest
        steps:
          - name: Call Sync Products API Endpoint
            env:
              CRON_SECRET: ${{ secrets.CRON_SECRET }}
              API_URL: https://renovarte2-0.vercel.app/api/sync-products # ¡REEMPLAZA ESTO!
            run: |
              response=$(curl -s -w "%{http_code}" -X GET \
                -H "Authorization: Bearer $CRON_SECRET" \
                "$API_URL")
              
              http_code=$(tail -n1 <<< "$response") # Extrae el código HTTP
              body=$(sed '$ d' <<< "$response")   # Extrae el cuerpo de la respuesta
              
              echo "Status Code: $http_code"
              echo "Response Body: $body"
              
              if [ "$http_code" -ne 200 ]; then
                echo "Error: API call failed with status code $http_code"
                exit 1
              fi
              echo "API call successful."