name: Sync Products Cron Job

on:
  schedule:
    # Ejecuta cada 10 minutos durante la hora 12 PM UTC.
    # Es decir, a las 12:00, 12:10, 12:20, 12:30, 12:40, 12:50 UTC.
    # Ajusta la zona horaria o el schedule si es necesario.
    - cron: '*/10 13 * * *'
  workflow_dispatch: {} # Permite ejecutarlo manualmente desde la pestaña Actions de GitHub

jobs:
  sync_external_products:
    runs-on: ubuntu-latest
    steps:
      - name: Call Sync Products API Endpoint
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          # Asegúrate que esta URL es la correcta para tu despliegue en Vercel:
          API_URL: https://renovarte2-0.vercel.app/api/sync-products
        run: |
          echo "Attempting to call API: $API_URL"
          response=$(curl -s -w "%{http_code}" -X GET \
            -H "Authorization: Bearer $CRON_SECRET" \
            "$API_URL")
          
          http_code=$(tail -n1 <<< "$response") # Extrae el código HTTP
          body=$(sed '$ d' <<< "$response")   # Extrae el cuerpo de la respuesta
          
          echo "Status Code: $http_code"
          echo "Response Body: $body"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error: API call failed with status code $http_code"
            exit 1
          fi
          echo "API call successful."
